[package]
name = "tx-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tx-engine = { path = "../tx-engine" }